spring:
  application:
    name: mozhi-app
  profiles:
    active: dev

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

mozhi:
  web:
    allowed-origins:
      - http://127.0.0.1:5173
      - http://localhost:5173
